### ISSUE TITLE
split out Octavian deps?

### ISSUE THREAD

**Issue by Roger-luo** [chriselrod/StrideArrays.jl#21]
I'm trying to use this package to replace PaddedMatrices in BQCESubroutines, where I don't need matrix multiplication but just the StrideArray type. And the package BQCESubroutine does not require multithreading by default. There is an annoying warning every time I use BQCESubroutines tho Octavian is not my direct dependency. It would be nice if I could use StrideArray as a lower-level dependency.

**Comment by chriselrod** [comment]
Does https://github.com/JuliaSIMD/StrideArraysCore.jl work?

**Comment by Roger-luo** [comment]
> It does depend on ThreadingUtilities.jl still, and defines the AbstractStrideArray abstract type.
I could move a little more there, like the definition of the actual StrideArray type if you'd like.

Yeah, this sounds good, I also want to use your CheapThread or ThreadingUtilities to support multithreading in the generic & specialized subspace matrix multiplication in BQCESubroutine.

> Which multithreading?

I meant the warning below, e.g you don't need to use `julia -t12` to use `BQCESubroutine` (there will be CUDA methods too)

> Which warning? Why should depending on StrideArrays give a warning if you aren't also directly depending on Octavian?
That is definitely not intended and something I was unaware of. Any more info/reproducer?

so if you use BQCESubroutine via `using BQCESubroutine` without any threading options, it will give you a warning as following

```julia
julia> using BQCESubroutine
┌ Warning: Your system has static(12) physical cores, but `Octavian.jl` only has 1 thread available. For the best performance, you should start Julia with at least static(12) threads.
└ @ Octavian ~/.julia/packages/Octavian/P5B9l/src/init.jl:11
```

but I'm not depending on Octavian

```toml
name = "BQCESubroutine"
uuid = "29e2bfda-5ba7-471c-9125-afac425f1f80"
authors = ["Roger-Luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
StrideArrays = "d1fa6d79-ef01-42a6-86c9-f7c551f8593b"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"
YaoLocations = "66df03fb-d475-48f7-b449-3d9064bf085b"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
```
